/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP2
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <UART_1.h>
#include <isr_1.h>
#include <ENGAGE_CLUTCH.h>
#include <ENGAGE_CLUTCH_aliases.h>
#include <UP_SHIFT_AIR.h>
#include <UP_SHIFT_AIR_aliases.h>
#include <DOWN_SHIFT_AIR.h>
#include <DOWN_SHIFT_AIR_aliases.h>
#include <UART_1_IntClock.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

