/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP3
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <Pin_1.h>
#include <Pin_1_aliases.h>
#include <Engage_Clutch.h>
#include <Engage_Clutch_aliases.h>
#include <Down_Shift_Air.h>
#include <Down_Shift_Air_aliases.h>
#include <Up_Shift_Air.h>
#include <Up_Shift_Air_aliases.h>
#include <Steering_Wheel.h>
#include <Steering_Wheel_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

