/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2C_MPU6050.h"
#include "I2C_MPU6050_I2C.h"
#include "I2C_MPU6050_PINS.h"
#include "I2C_MPU6050_I2C_PVT.h"
#include "I2C_MPU6050_PVT.h"
#include "I2C_MPU6050_BOOT.h"
#include "UART_1.h"
#include "Clock_1.h"
#include "I2C_MPU6050_sda.h"
#include "I2C_MPU6050_sda_aliases.h"
#include "I2C_MPU6050_scl.h"
#include "I2C_MPU6050_scl_aliases.h"
#include "I2C_MPU6050_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"

/*[]*/

